import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  fleetNumber: DS.attr('string'),
  date: DS.attr('string'),

  // inspections
  cabWarningDevices: DS.attr('boolean'),
  wipersWashHorn: DS.attr('boolean'),
  demisters: DS.attr('boolean'),
  mirrors: DS.attr('boolean'),
  handBrake: DS.attr('boolean'),
  directIndicators: DS.attr('boolean'),
  fireExtinguishers: DS.attr('boolean'),
  floorThreads: DS.attr('boolean'),
  driversSeat: DS.attr('boolean'),
  passengerSeats: DS.attr('boolean'),
  handPoles: DS.attr('boolean'),
  bells: DS.attr('boolean'),
  emergencyExitHammers: DS.attr('boolean'),
  interiorLights: DS.attr('boolean'),
  TFTScreen: DS.attr('boolean'),
  wheelchairRamp: DS.attr('boolean'),
  EntranceDoor: DS.attr('boolean'),
  stepLights: DS.attr('boolean'),
  licenseDiscs: DS.attr('boolean'),
  windscreen: DS.attr('boolean'),
  exteriorLights: DS.attr('boolean'),
  wheelsNutsTyres: DS.attr('boolean'),
  bodyPanels: DS.attr('boolean'),
  fuelFilterCup: DS.attr('boolean'),
  oilWaterFuelLicks: DS.attr('boolean'),
  emergencyExitExternal: DS.attr('boolean'),
  bonnetsFlapsDoors: DS.attr('boolean'),
  exhaustSmoke: DS.attr('boolean'),
  destinationEquipment: DS.attr('boolean'),
  CCTV: DS.attr('boolean')
}).reopenClass({
	FIXTURES: [
		{
			id: 1,
			name: 'Tom Watson',
			fleetNumber: '850',
			date: '05.05.2015',

      // inspections
      cabWarningDevices: true,
      wipersWashHorn: true,
      demisters: true,
      mirrors: true,
      handBrake: true,
      directIndicators: false,
      fireExtinguishers: false,
      floorThreads: true,
      driversSeat: true,
      passengerSeats: false,
      handPoles: true,
      bells: true,
      emergencyExitHammers: true,
      interiorLights: false,
      TFTScreen: true,
      wheelchairRamp: true,
      EntranceDoor: false,
      stepLights: true,
      licenseDiscs: true,
      windscreen: true,
      exteriorLights: true,
      wheelsNutsTyres: true,
      bodyPanels: true,
      fuelFilterCup: true,
      oilWaterFuelLicks: true,
      emergencyExitExternal: true,
      bonnetsFlapsDoors: true,
      exhaustSmoke: true,
      destinationEquipment: true,
      CCTV: true
		},
		{
			id: 2,
			name: 'Tom Watson',
			fleetNumber: '750',
			date: '05.04.2015',

      // inspections
      cabWarningDevices: false,
      wipersWashHorn: false,
      demisters: true,
      mirrors: true,
      handBrake: true,
      directIndicators: false,
      fireExtinguishers: true,
      floorThreads: false,
      driversSeat: true,
      passengerSeats: true,
      handPoles: true,
      bells: true,
      emergencyExitHammers: false,
      interiorLights: true,
      TFTScreen: true,
      wheelchairRamp: true,
      EntranceDoor: true,
      stepLights: true,
      licenseDiscs: true,
      windscreen: true,
      exteriorLights: true,
      wheelsNutsTyres: true,
      bodyPanels: true,
      fuelFilterCup: true,
      oilWaterFuelLicks: true,
      emergencyExitExternal: true,
      bonnetsFlapsDoors: true,
      exhaustSmoke: true,
      destinationEquipment: true,
      CCTV: true
		},
		{
			id: 3,
			name: 'Tom Watson',
			fleetNumber: '500',
			date: '05.03.2015',

      // inspections
      cabWarningDevices: false,
      wipersWashHorn: true,
      demisters: true,
      mirrors: true,
      handBrake: true,
      directIndicators: true,
      fireExtinguishers: true,
      floorThreads: true,
      driversSeat: true,
      passengerSeats: true,
      handPoles: true,
      bells: false,
      emergencyExitHammers: true,
      interiorLights: true,
      TFTScreen: true,
      wheelchairRamp: true,
      EntranceDoor: true,
      stepLights: true,
      licenseDiscs: false,
      windscreen: false,
      exteriorLights: true,
      wheelsNutsTyres: true,
      bodyPanels: true,
      fuelFilterCup: true,
      oilWaterFuelLicks: true,
      emergencyExitExternal: true,
      bonnetsFlapsDoors: true,
      exhaustSmoke: true,
      destinationEquipment: false,
      CCTV: true
		},
    {
      id: 4,
      name: 'Tom Watson',
      fleetNumber: '500',
      date: '05.02.2015',

      // inspections
      cabWarningDevices: true,
      wipersWashHorn: true,
      demisters: true,
      mirrors: true,
      handBrake: true,
      directIndicators: true,
      fireExtinguishers: true,
      floorThreads: true,
      driversSeat: false,
      passengerSeats: true,
      handPoles: true,
      bells: true,
      emergencyExitHammers: true,
      interiorLights: true,
      TFTScreen: true,
      wheelchairRamp: true,
      EntranceDoor: false,
      stepLights: false,
      licenseDiscs: true,
      windscreen: true,
      exteriorLights: true,
      wheelsNutsTyres: true,
      bodyPanels: false,
      fuelFilterCup: true,
      oilWaterFuelLicks: true,
      emergencyExitExternal: true,
      bonnetsFlapsDoors: true,
      exhaustSmoke: true,
      destinationEquipment: false,
      CCTV: true
    },
    {
      id: 5,
      name: 'Tom Watson',
      fleetNumber: '550',
      date: '05.01.2015',

      // inspections
      cabWarningDevices: false,
      wipersWashHorn: true,
      demisters: true,
      mirrors: true,
      handBrake: true,
      directIndicators: false,
      fireExtinguishers: true,
      floorThreads: true,
      driversSeat: true,
      passengerSeats: false,
      handPoles: true,
      bells: true,
      emergencyExitHammers: true,
      interiorLights: true,
      TFTScreen: true,
      wheelchairRamp: false,
      EntranceDoor: true,
      stepLights: true,
      licenseDiscs: true,
      windscreen: true,
      exteriorLights: true,
      wheelsNutsTyres: true,
      bodyPanels: true,
      fuelFilterCup: true,
      oilWaterFuelLicks: true,
      emergencyExitExternal: true,
      bonnetsFlapsDoors: true,
      exhaustSmoke: true,
      destinationEquipment: true,
      CCTV: true
    }
	]
});

